export const runtime = 'nodejs'

const mockSections = {
  home: [
    {
      id: '1',
      page: 'home',
      sectionType: 'hero',
      title: 'Home Hero',
      subtitle: 'Enterprise Risk Platform',
      heading: 'Run catastrophe models in seconds',
      description: 'Release billions in trapped capital',
      backgroundStyle: 'light-institutional',
      order: 1,
      published: true,
      videoUrl: '/uploads/hero-background.mp4',
      imageUrl: '/uploads/dashboard-screenshot.png',
      buttonText: 'Start Free Trial',
      buttonUrl: '/signup',
      secondaryButtonText: 'Learn More',
      secondaryButtonUrl: '/platform',
    },
    {
      id: '2',
      page: 'home',
      sectionType: 'feature-grid',
      title: 'Home Features',
      heading: 'Enterprise-Grade Capabilities',
      description: 'Built for institutional investors and risk managers',
      backgroundStyle: 'light',
      order: 2,
      published: true,
      items: [
        {
          icon: '⚡',
          title: 'Lightning Fast',
          description: 'Run models in seconds, not hours',
          status: 'validated',
        },
        {
          icon: '🔒',
          title: 'Enterprise Security',
          description: 'SOC 2 Type II compliant infrastructure',
          status: 'validated',
        },
        {
          icon: '📊',
          title: 'Advanced Analytics',
          description: 'Deep insights into catastrophe risk',
          status: 'validated',
        },
        {
          icon: '🌍',
          title: 'Global Coverage',
          description: 'Models for perils worldwide',
          status: 'validated',
        },
      ],
    },
    {
      id: '3',
      page: 'home',
      sectionType: 'cta',
      title: 'Home CTA',
      heading: 'Ready to transform your risk analysis?',
      description: 'Join leading institutions using QRS for better decisions',
      backgroundStyle: 'deep-dark',
      order: 3,
      published: true,
      buttonText: 'Get Started Free',
      buttonUrl: '/signup',
    },
  ],
  platform: [
    {
      id: '4',
      page: 'platform',
      sectionType: 'hero',
      title: 'Platform Hero',
      subtitle: 'Advanced Platform',
      heading: 'Powerful Risk Modeling Platform',
      description: 'Integrated tools for catastrophe risk analysis',
      backgroundStyle: 'light-institutional',
      order: 1,
      published: true,
      imageUrl: '/uploads/platform-dashboard.png',
      buttonText: 'Explore Features',
      buttonUrl: '#features',
    },
    {
      id: '5',
      page: 'platform',
      sectionType: 'feature-grid',
      title: 'Platform Features',
      heading: 'Complete Risk Management Suite',
      description: 'Everything you need for comprehensive catastrophe risk analysis',
      backgroundStyle: 'light',
      order: 2,
      published: true,
      items: [
        {
          icon: '📈',
          title: 'Portfolio Analysis',
          description: 'Analyze risk across your entire portfolio',
          status: 'validated',
        },
        {
          icon: '🔍',
          title: 'Detailed Reports',
          description: 'Comprehensive risk reports and metrics',
          status: 'validated',
        },
        {
          icon: '🔗',
          title: 'API Integration',
          description: 'Integrate with your existing systems',
          status: 'validated',
        },
        {
          icon: '⚙️',
          title: 'Customization',
          description: 'Tailor the platform to your needs',
          status: 'validated',
        },
      ],
    },
  ],
  solutions: [
    {
      id: '6',
      page: 'solutions',
      sectionType: 'hero',
      title: 'Solutions Hero',
      subtitle: 'Industry Solutions',
      heading: 'Solutions for Every Risk Profile',
      description: 'Tailored approaches for different institutional needs',
      backgroundStyle: 'light-institutional',
      order: 1,
      published: true,
      buttonText: 'View Solutions',
      buttonUrl: '#solutions',
    },
    {
      id: '7',
      page: 'solutions',
      sectionType: 'feature-grid',
      title: 'Solutions Grid',
      heading: 'Industry-Specific Solutions',
      description: 'Purpose-built for insurance, reinsurance, and alternative risk transfer',
      backgroundStyle: 'light',
      order: 2,
      published: true,
      items: [
        { icon: '🏢', title: 'Insurance', description: 'Underwriting and portfolio management', status: 'validated' },
        { icon: '🌐', title: 'Reinsurance', description: 'Treaty evaluation and pricing', status: 'validated' },
        { icon: '💼', title: 'Asset Owners', description: 'Portfolio risk assessment', status: 'validated' },
        { icon: '🎯', title: 'Capital Markets', description: 'Securitization and risk transfer', status: 'validated' },
      ],
    },
  ],
  regulatory: [
    {
      id: '8',
      page: 'regulatory',
      sectionType: 'hero',
      title: 'Regulatory Hero',
      subtitle: 'Compliance & Regulation',
      heading: 'Meet Global Regulatory Requirements',
      description: 'Compliant with major international frameworks',
      backgroundStyle: 'light-institutional',
      order: 1,
      published: true,
      buttonText: 'View Compliance',
      buttonUrl: '#compliance',
    },
    {
      id: '9',
      page: 'regulatory',
      sectionType: 'feature-grid',
      title: 'Regulatory Frameworks',
      heading: 'Supporting Major Regulations',
      description: 'Comprehensive support for global regulatory requirements',
      backgroundStyle: 'light',
      order: 2,
      published: true,
      items: [
        { icon: '✓', title: 'Solvency II', description: 'EU insurance regulation compliant', status: 'validated' },
        { icon: '✓', title: 'NAIC Model Law', description: 'US insurance regulatory framework', status: 'validated' },
        { icon: '✓', title: 'Basel III', description: 'Banking capital requirements', status: 'validated' },
        { icon: '✓', title: 'EIOPA Guidelines', description: 'European supervisory guidelines', status: 'validated' },
      ],
    },
  ],
  trust: [
    {
      id: '10',
      page: 'trust',
      sectionType: 'hero',
      title: 'Trust Hero',
      subtitle: 'Trust & Security',
      heading: 'Enterprise-Grade Security & Compliance',
      description: 'Your data security is our top priority',
      backgroundStyle: 'light-institutional',
      order: 1,
      published: true,
      buttonText: 'Read Security Report',
      buttonUrl: '/security',
    },
    {
      id: '11',
      page: 'trust',
      sectionType: 'feature-grid',
      title: 'Security Features',
      heading: 'Industry-Leading Security',
      description: 'Multiple layers of protection for your data',
      backgroundStyle: 'light',
      order: 2,
      published: true,
      items: [
        { icon: '🔐', title: 'SOC 2 Type II', description: 'Independently audited and certified', status: 'validated' },
        { icon: '🛡️', title: 'Encryption', description: 'End-to-end encryption for all data', status: 'validated' },
        { icon: '🔍', title: 'Compliance', description: 'GDPR, HIPAA, and other standards', status: 'validated' },
        { icon: '⚡', title: 'Monitoring', description: '24/7 security monitoring', status: 'validated' },
      ],
    },
  ],
  verify: [
    {
      id: '12',
      page: 'verify',
      sectionType: 'hero',
      title: 'Verify Hero',
      subtitle: 'Verification & Validation',
      heading: 'Model Validation & Verification',
      description: 'Rigorous testing and validation processes',
      backgroundStyle: 'light-institutional',
      order: 1,
      published: true,
      buttonText: 'View Reports',
      buttonUrl: '#reports',
    },
    {
      id: '13',
      page: 'verify',
      sectionType: 'feature-grid',
      title: 'Verification Methods',
      heading: 'Comprehensive Validation',
      description: 'Our models undergo rigorous testing',
      backgroundStyle: 'light',
      order: 2,
      published: true,
      items: [
        { icon: '🔬', title: 'Scientific Testing', description: 'Peer-reviewed validation', status: 'validated' },
        { icon: '📊', title: 'Backtesting', description: 'Historical accuracy verification', status: 'validated' },
        { icon: '🎯', title: 'Industry Benchmarks', description: 'Compared against industry standards', status: 'validated' },
        { icon: '✅', title: 'Continuous Improvement', description: 'Regular model updates and refinements', status: 'validated' },
      ],
    },
  ],
  about: [
    {
      id: '14',
      page: 'about',
      sectionType: 'hero',
      title: 'About Hero',
      subtitle: 'About QRS',
      heading: 'Transforming Risk Management',
      description: 'Leading innovation in catastrophe risk modeling',
      backgroundStyle: 'light-institutional',
      order: 1,
      published: true,
      buttonText: 'Contact Us',
      buttonUrl: '/contact',
    },
    {
      id: '15',
      page: 'about',
      sectionType: 'feature-grid',
      title: 'About Points',
      heading: 'Why Choose QRS',
      description: 'What sets us apart in the industry',
      backgroundStyle: 'light',
      order: 2,
      published: true,
      items: [
        { icon: '🚀', title: 'Innovation', description: 'Cutting-edge risk modeling technology', status: 'validated' },
        { icon: '👥', title: 'Expertise', description: 'Team of world-class scientists', status: 'validated' },
        { icon: '🌍', title: 'Global Reach', description: 'Serving clients worldwide', status: 'validated' },
        { icon: '💡', title: 'Thought Leadership', description: 'Advancing the industry forward', status: 'validated' },
      ],
    },
  ],
}

export async function GET(request: Request) {
  const url = new URL(request.url)
  const page = url.searchParams.get('page') || 'home'

  try {
    const sections = mockSections[page as keyof typeof mockSections] || []
    return Response.json({
      docs: sections,
      totalDocs: sections.length,
      limit: 100,
      totalPages: 1,
      page: 1,
    })
  } catch (error) {
    return Response.json({ error: 'Failed to fetch sections' }, { status: 500 })
  }
}
